# Generated by Django 2.1.5 on 2019-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
