# Generated by Django 2.1.5 on 2019-03-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190323_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.ManyToManyField(to='api.Genres'),
        ),
    ]
